ecs: add v8 alias to v1 implementation
logstash-plugins/logstash-input-syslog pull request #68
Opened 2021-07-28 17:25 UTC by yaauie

2021-07-29 06:41 UTC, kares approved these changes
:cherries:

2021-07-29 10:12 UTC, kares approved these changes
:ice_cream:

2021-07-29 10:17 UTC, kares requested changes
sorry wrong tab on previous :heavy_check_mark: 

since we need to pass [`ecs_compatibility` to the grok filter](https://github.com/logstash-plugins/logstash-input-syslog/blob/v3.5.0/lib/logstash/inputs/syslog.rb#L107) we need to make sure logstash-filter-grok is updated first and it's version requirement is updated afterwards with v8 support, sample failing test:

https://app.travis-ci.com/github/logstash-plugins/logstash-input-syslog/jobs/527490671#L516-L517

2021-11-05 22:41 UTC, yaauie commented
upstream grok PR https://github.com/logstash-plugins/logstash-filter-grok/pull/175

2021-11-05 22:58 UTC, yaauie commented on CHANGELOG.md
> +  - Add support for ECS v8 as alias to v1 implementation
```suggestion
  - Add support for ECS v8 as alias to v1 implementation [#68](https://github.com/logstash-plugins/logstash-input-syslog/pull/68)
```

2021-11-08 05:51 UTC, kares approved these changes
LGTM, the failing CI against 8.0-SNAPSHOT is unrelated

(an issue with timestamp formatting due changes in LS 8.0 e.g. `expected: "2021-10-26T20:19:25.000Z" got: "2021-10-26T20:19:25Z"`)

2021-11-10 20:05 UTC, yaauie commented
@kares I resolved the failing spec on LS8 with a8c0036 which uses a helper introduced in devutils 2.3 to make assertions about timestamps that are not bound to the serialization length.

2021-11-11 08:49 UTC, kares approved these changes
LGTM, :green_heart: CI

2021-11-11 18:48 UTC, merged